version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ${PROJECT_PATH}/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - lakehouse

networks:
  lakehouse:
    driver: bridge